"""add_performance_metrics_tables

Revision ID: 58c78f7619d1
Revises: 56b4ec9191cb
Create Date: 2025-12-03 22:56:01.418459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c78f7619d1'
down_revision: Union[str, Sequence[str], None] = '56b4ec9191cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_endpoint_time', 'system_metrics', ['endpoint', 'timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_endpoint'), 'system_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_system_metrics_status_code'), 'system_metrics', ['status_code'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_user_id'), 'system_metrics', ['user_id'], unique=False)
    op.create_table('valuation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valuation_id', sa.String(), nullable=True),
    sa.Column('method_type', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('input_complexity_score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['valuation_id'], ['valuation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_valuation_method_created', 'valuation_metrics', ['method_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_valuation_metrics_created_at'), 'valuation_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_valuation_metrics_method_type'), 'valuation_metrics', ['method_type'], unique=False)
    op.create_index(op.f('ix_valuation_metrics_start_time'), 'valuation_metrics', ['start_time'], unique=False)
    op.create_index(op.f('ix_valuation_metrics_user_id'), 'valuation_metrics', ['user_id'], unique=False)
    op.create_index(op.f('ix_valuation_metrics_valuation_id'), 'valuation_metrics', ['valuation_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_valuation_metrics_valuation_id'), table_name='valuation_metrics')
    op.drop_index(op.f('ix_valuation_metrics_user_id'), table_name='valuation_metrics')
    op.drop_index(op.f('ix_valuation_metrics_start_time'), table_name='valuation_metrics')
    op.drop_index(op.f('ix_valuation_metrics_method_type'), table_name='valuation_metrics')
    op.drop_index(op.f('ix_valuation_metrics_created_at'), table_name='valuation_metrics')
    op.drop_index('idx_valuation_method_created', table_name='valuation_metrics')
    op.drop_table('valuation_metrics')
    op.drop_index(op.f('ix_system_metrics_user_id'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_status_code'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_endpoint'), table_name='system_metrics')
    op.drop_index('idx_system_endpoint_time', table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
